services:

  clickhouse_21_3:
    image: clickhouse/clickhouse-server:21.3
    volumes:
      - ./default_user.xml:/etc/clickhouse-server/users.d/default_user.xml
      - ./z_config.xml:/etc/clickhouse-server/config.d/z_config.xml
    ports:
      - "8001:9000"
      - "9123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - clickhouse

  clickhouse_23_1:
    image: clickhouse/clickhouse-server:23.1
    ports:
     - "8002:9000"
     - "9124:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - clickhouse

  clickhouse_24_4:
    image: clickhouse/clickhouse-server:24.4
    volumes:
      - ./default_user.xml:/etc/clickhouse-server/users.d/default_user.xml
      - ./z_config.xml:/etc/clickhouse-server/config.d/z_config.xml
    ports:
      - "8004:9000"
      - "9126:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - clickhouse

 clickhouse_25_1:
    image: clickhouse/clickhouse-server:25.1
    volumes:
      - ./default_user.xml:/etc/clickhouse-server/users.d/default_user.xml
      - ./z_config.xml:/etc/clickhouse-server/config.d/z_config.xml
    ports:
      - "8006:9000"
      - "9128:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - clickhouse

  clickhouse_25_4:
    image: clickhouse/clickhouse-server:25.4
    volumes:
      - ./default_user.xml:/etc/clickhouse-server/users.d/default_user.xml
      - ./z_config.xml:/etc/clickhouse-server/config.d/z_config.xml
    ports:
      - "8005:9000"
      - "9127:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - clickhouse

networks:
  clickhouse:
    driver: bridge

